/**
 * 전체 레이아웃
 */
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/css/style.css";
import Header from "@/components/common/Header.js";
import { AuthProvider } from "@/context/AuthContext.js";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "JILoL.gg",
  description: "Generated by create next app",
};

// 헤더를 모든 페이지에서 공통으로 사용
export default function RootLayout({ children }) {
    return (
        <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
            {/* AuthProvider로 앱 전체를 감싸기 */}
            <AuthProvider>
                <Header />
                {children}
            </AuthProvider>
        </body>
        </html>
    );
}
