services:

# Application
  my_app:   # 서비스명 지정 가능
    container_name: app_container  # 컨테이너 이름 지정
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Seoul
      # 1) 로컬 db (windows 운영체제)
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/basic
      # 2) 로컬 DB (리눅스 운영체제). ec2의 경우 ip 고정 아니라 변경되면 바꿔야함
      - SPRING_DATASOURCE_URL=jdbc:postgresql://172.31.42.140:5432/basic
      # 3) Docker 내부 컨테이너 db 사용할 때 아래 URL 사용
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://docker_db:5432/basic
      - SPRING_DATASOURCE_USERNAME=jikim
      - SPRING_DATASOURCE_PASSWORD_FILE=/run/secrets/db-password
#    depends_on:
#      - docker_db
#    command: [ "java", "-Duser.timezone=Asia/Seoul", "-jar", "app.jar" ]
    networks:
      - app-network

# Postgres DB (미사용)
  docker_db:   # 서비스명 지정 가능
    container_name: db_container  # 컨테이너 이름 지정
    image: postgres
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data  # DB 데이터를 컨테이너 바깥(EC2 내부) 볼륨 마운트
#      - ./src/main/resources/db/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql  # 초기화 SQL 스크립트 추가
    environment:
      - POSTGRES_DB=basic
      - POSTGRES_USER=jikim
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "jikim", "-d", "basic" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network
volumes:
  db-data:
  postgres_data:
    driver: local

secrets:
  db-password:
      file: ./src/main/resources/db/postgres/password.txt

# 같은 네트워크를 사용하면 컨테이너 이름으로 서로 통신 가능
networks:
  app-network:
    driver: bridge

