# Database (PostgreSQL)
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://localhost:5432/basic
# 윈도우 환경에서 도커 컨테이너 배포 시
#spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/basic
spring.datasource.username=jikim
spring.datasource.password=jikim

# Spring Boot SQL 설정
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:/db/postgres/schema.sql
spring.sql.init.data-locations=classpath:/db/postgres/data.sql

# SQL 출력 설정
#spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

# Spring Batch 설정
## 기본 제공 스키마 파일을 실행하여 Job 실행 상태, 이력 등을 저장할 메타 테이블 생성
## spring-batch-core-*.jar 안에 있는 DDL 스크립트를 DB에 실행
spring.batch.jdbc.initialize-schema=always
## 스프링 컨텍스트에 등록된 첫 번째 Job 자동 실행x
spring.batch.job.enabled=false

# Swagger UI 설정
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/api/swagger-ui
springdoc.api-docs.path=/api/v3/api-docs
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.try-it-out-enabled=true

# Redis 설정
spring.data.redis.host=54.180.118.74
spring.data.redis.port=36379
spring.data.redis.password=jikim_pwdForRedis_250419
spring.data.redis.timeout=2000

# Redisson
logging.level.org.redisson=debug

