server:
  port: 8080
spring:
  application:
    name: basic
  profiles:
    # 환경변수로 오버라이드 가능
    default: ${SPRING_PROFILES_ACTIVE:prod}

  # 캐시 설정
  cache:
    type: redis
  autoconfigure:
    exclude:
      - org.redisson.spring.starter.RedissonAutoConfigurationV2  # 캐시 자동설정만 비활성화

  # JPA 배치 설정
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 50    # 배치 사이즈
        order_inserts: true # INSERT 순서 최적화
        order_updates: true # UPDATE 순서 최적화
        batch_versioned_data: true

  # 정적 파일 설정
  mvc:
    static-path-pattern: /**

  # 뷰템플릿 설정 (Thymeleaf)
  thymeleaf:
    enabled: true
    mode: HTML
    encoding: UTF-8
    cache: false
    check-template-location: true

# actuator 모니터링
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,configprops,beans,loggers,threaddump,mappings
  endpoint:
    health:
      show-details: when-authorized


# logging 설정
logging:
  config: classpath:logback-spring.xml
  level:
    # 쿼리 로그
    org.hibernate.SQL: INFO  # 실제 실행되는 SQL 쿼리
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # 바인딩 파라미터 값 출력
    org.hibernate.engine.internal.StatefulPersistenceContext: WARN  # 1차 캐시 관련 디버깅 로그
    org.springframework.orm.jpa: ERROR


jwt:
  private:
    key: classpath:jwt/app.key
  public:
    key: classpath:jwt/app.pub

uploads:
  path: uploads/


# https://developer.riotgames.com/
lol:
  esports:
    api:
      url: https://esports-api.lolesports.com
      key: 0TvQnueqKa5mxJntVWt0w4LpLfEkrV1Ta8rQBb9Z

# 쿠키 정책 설정 (로컬 http/https 프론트 <-> 로컬 http 백엔드)
cookie:
  secure: true
  same-site: None

# Swagger OpenAPI
springdoc:
  swagger-ui:
    csrf:
      enabled: true
    with-credentials: true
    filter: true
