# Database (PostgreSQL)
spring.datasource.url=jdbc:postgresql://172.31.46.219:5432/basic?sslmode=require
spring.datasource.username=jikim
spring.datasource.password=jikim
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Spring Boot? resources/data.sql ??? ?? ??? ???
# ?????, ???(-)? ?? ???? SQL ??? ?? ???? ????? ?? ???? ??? ? ????.
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always
# schema.sql, data.sql ?? ??
spring.sql.init.schema-locations=classpath:/db/postgres/schema.sql  
spring.sql.init.data-locations=classpath:/db/postgres/data.sql

# ?? ?? SQL ??? ??? ?? (?? ??? ???? ??)
#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

# Swagger UI ??
# API ?? (JSON) ?? ??
springdoc.api-docs.enabled=true
# Swagger UI ???
springdoc.swagger-ui.enabled=true
# Swagger UI ?? ?? ??
springdoc.swagger-ui.path=/swagger-ui
# API Docs URL ?? ?? (??: /v3/api-docs -> /v3/api-docs)
springdoc.api-docs.path=/api/v3/api-docs
# Swagger UI ?? URL? ???? ??? ??
springdoc.swagger-ui.disable-swagger-default-url=true
# API ??? ?? ??? ???? ?? (alpha: ??? ?, method: HTTP ??? ??? ??)
springdoc.swagger-ui.operations-sorter=alpha
# API ??? ??? ???? ?? (?? ??? ???? ??)
#springdoc.swagger-ui.tags-sorter=method
# Try it out ??? ???? Swagger UI?? ??? API ??? ???? ? ??? ??
springdoc.swagger-ui.try-it-out-enabled=true
# API ?? ??? ??? (???? OpenAPI ??? ????? ??)
springdoc.api-docs.groups.enabled=true
# Swagger UI?? ??? ???? ?? ?? ??
springdoc.swagger-ui.default-model-expand-depth=1
springdoc.swagger-ui.default-models-expand-depth=1
