# Database (H2 in-memory)
# DATABASE_TO_UPPER: H2 데이터베이스가 자동으로 대문자 변환하지 않도록 설정
spring.datasource.url=jdbc:h2:mem:testdb;MODE=MySQL;DATABASE_TO_UPPER=false;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate & JPA 설정
## 사용할 데이터베이스의 Hibernate Dialect 설정 (H2 데이터베이스 사용)
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
## DDL 자동 생성 및 삭제 설정 (앱 실행 시 테이블 생성, 종료 시 삭제)
spring.jpa.hibernate.ddl-auto=create-drop
## 애플리케이션 실행 후 데이터 소스 초기화 지연 (SQL 스크립트 실행이 필요할 때 사용)
spring.jpa.defer-datasource-initialization=true
## 테이블 및 컬럼 이름을 따옴표로 감싸지 않도록 설정 (DBMS에 따라 동작 방식이 달라질 수 있음)
spring.jpa.properties.hibernate.globally_quoted_identifiers=true

# SQL 로그 설정 (Hibernate SQL 출력 관련 설정)
# 실행된 SQL을 콘솔에 한줄로 출력 (들여쓰기 or sql 바인딩 없음)
#spring.jpa.show-sql=true
## 실행된 SQL 쿼리를 보기 좋게 정렬 (들여쓰기)
spring.jpa.properties.hibernate.format_sql=true
## SQL 실행 시 주석을 포함해서 출력 (JPQL → SQL 변환 과정 포함)
spring.jpa.properties.hibernate.use_sql_comments=true
## Hibernate의 SQL 실행 로그를 출력 (DEBUG 레벨)
logging.level.org.hibernate.SQL=DEBUG
## SQL 바인딩된 값(파라미터 값)까지 출력 (TRACE 레벨)
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# H2 Console 설정
## H2 Database Console 활성화
spring.h2.console.enabled=true
## H2 Console에 접근할 수 있는 URL 설정 (예: http://localhost:8080/h2-console)
spring.h2.console.path=/h2-console
