# Database (PostgreSQL)
spring.datasource.url=jdbc:postgresql://172.31.46.219:5432/basic?sslmode=require
spring.datasource.username=jikim
spring.datasource.password=jikim
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Spring Boot에서 resources/data.sql 파일을 두면 
# 애플리케이션 실행 시 기본적으로 자동으로 실행되도록 하기 위한 설정 (h2 같은 내장 db일 땐 불필요)
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always
# schema.sql, data.sql 경로 변경
spring.sql.init.schema-locations=classpath:/db/postgres/schema.sql  
spring.sql.init.data-locations=classpath:/db/postgres/data.sql      

# 실행한 SQL 쿼리 로그 출력
#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true


# Swagger UI 설정
# API 문서 (JSON) 활성화
springdoc.api-docs.enabled=true
# Swagger UI 활성화
springdoc.swagger-ui.enabled=true
# Swagger UI 접속 경로 변경 (기본: /swagger-ui.html)
springdoc.swagger-ui.path=/swagger
# 기본 Swagger UI URL을 비활성화 (ex: /swagger-ui.html 대신 /swagger만 사용)
springdoc.swagger-ui.disable-swagger-default-url=true
# API 목록 정렬 기준 (alpha: 알파벳순, method: HTTP 메서드 순)
springdoc.swagger-ui.operations-sorter=alpha
# API 설명 정렬 기준 (alpha: 알파벳순, method: HTTP 메서드 순)
#springdoc.swagger-ui.tags-sorter=method
# Try it out 버튼에서 기본 요청 Parameter 값 자동 설정
springdoc.swagger-ui.try-it-out-enabled=true
# API 문서 요청 시 group 설정 가능 (여러 개의 OpenAPI 문서가 있는 경우)
springdoc.api-docs.groups.enabled=true
# 기본 요청 헤더 Accept/Content-Type 자동 추가
springdoc.swagger-ui.default-model-expand-depth=1
springdoc.swagger-ui.default-models-expand-depth=1