server:
  port: 8080
spring:
  application:
    name: basic
  profiles:
    # 환경변수로 오버라이드 가능
    default: ${SPRING_PROFILES_ACTIVE:prod}

  # 정적 파일 설정
  mvc:
    static-path-pattern: /**

  # 뷰템플릿 설정 (Thymeleaf)
  thymeleaf:
    enabled: true
    mode: HTML
    encoding: UTF-8
    cache: false
    check-template-location: true

# logging 설정
logging:
  config: classpath:logback-spring.xml

jwt:
  private:
    key: classpath:jwt/app.key
  public:
    key: classpath:jwt/app.pub

uploads:
  path: uploads/


# https://developer.riotgames.com/
lol:
  esports:
    api:
      url: https://esports-api.lolesports.com
      key: 0TvQnueqKa5mxJntVWt0w4LpLfEkrV1Ta8rQBb9Z

# 쿠키 정책 설정 (로컬 http/https 프론트 <-> 로컬 http 백엔드)
cookie:
  secure: true
  same-site: None

springdoc:
  swagger-ui:
    csrf:
      enabled: true
    with-credentials: true
    filter: true
