# Application properties 공통 설정
server.port=8080

spring.application.name=basic
spring.profiles.active=dev

# 정적 파일 설정
spring.webflux.static-path-pattern=classpath:/resources/
spring.mvc.static-path-pattern=/**

# 뷰템플릿 설정 (Thymeleaf)
spring.thymeleaf.enabled=true
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false
spring.thymeleaf.check-template-location=true

