spring.application.name=basic


# H2 ???? DB ??
# DATABASE_TO_UPPER: H2 데이터베이스가 자동으로 대문자 변환하지 않도록 설정
spring.datasource.url=jdbc:h2:mem:testdb;MODE=MySQL;DATABASE_TO_UPPER=false;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate ?? (DB ?? ???)
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# ddl-auto: create-drop - 애플리케이션 시작 시 테이블 생성, 종료 시 테이블 삭제
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true
# 테이블명, 컬럼명을 따옴표로 감싸지 않도록 설정
spring.jpa.properties.hibernate.globally_quoted_identifiers=true

# 실행한 SQL 쿼리가 로그에 출력
#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
# Hibernate SQL 로그를 활성화
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
