-- data.sql 보다 먼저 실행됨

CREATE TABLE IF NOT EXISTS "users" (
     "id" bigint generated by default as identity,
     "password" varchar(255),
     "email" varchar(255) unique,
     "name" varchar(255),
     "authority" varchar(255) default 'SCOPE_USER',
     "profile_image_url" varchar(255),
     "created_dt" timestamp(6),
     "updated_dt" timestamp(6),
     primary key ("id")
);

CREATE TABLE IF NOT EXISTS "leagues"
(
    "id"               bigint generated by default as identity PRIMARY KEY,
    "league_id"        VARCHAR(64)  NOT NULL UNIQUE,
    "slug"             VARCHAR(300) NOT NULL,
    "name"             VARCHAR(300) NOT NULL,
    "region"           VARCHAR(50),
    "image"            TEXT,
    "priority"         INT,
    "display_position" INT,
    "display_status"   VARCHAR(50),
    "created_at"       TIMESTAMP,
    "updated_at"       TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "tournaments"
(
    "id"            bigint generated by default as identity PRIMARY KEY,
    "tournament_id" VARCHAR(64) NOT NULL UNIQUE,
    "slug"          VARCHAR(300),
    "start_date"    TIMESTAMP,
    "end_date"      TIMESTAMP,
    "league_id"     VARCHAR(64) NOT NULL
    -- 외래키 추가 가능: REFERENCES leagues(league_id)
);

CREATE TABLE IF NOT EXISTS "matches"
(
    "id"         bigint generated by default as identity PRIMARY KEY,
    "match_id"   VARCHAR(64) NOT NULL UNIQUE,
    "league_id"  VARCHAR(64) NOT NULL,
    "tournament_id"  VARCHAR(64),
    "start_time" TIMESTAMP,
    "state"      VARCHAR(50),
    "block_name" VARCHAR(100),
    "game_count" INT,
    "strategy"   VARCHAR(50)
    -- 외래키 추가 가능: REFERENCES leagues(league_id)
);
-- 날짜 비교 조회 시 인덱스 범위 스캔 목적
DROP INDEX IF EXISTS idx_match_start_time;
CREATE INDEX idx_match_start_time ON "matches" ("start_time");


CREATE TABLE IF NOT EXISTS "match_teams"
(
    "id"        bigint generated by default as identity PRIMARY KEY,
    "match_id"  VARCHAR(64) NOT NULL,
    "team_id"   VARCHAR(64) NOT NULL,
    "outcome"    VARCHAR(20),
    "game_wins" INT
    -- 외래키 추가 가능: REFERENCES matches(match_id), teams(team_code)
);

CREATE TABLE IF NOT EXISTS "teams"
(
    "id"          bigint generated by default as identity PRIMARY KEY,
    "team_id"     VARCHAR(64) NOT NULL,
    "slug"        VARCHAR(150) NOT NULL,
    "code"        VARCHAR(64)  NOT NULL,
    "name"        VARCHAR(150) NOT NULL,
    "image"       TEXT         NOT NULL,
    "league_id" VARCHAR(64),
    unique ("team_id")
);

----------------------
CREATE TABLE IF NOT EXISTS "user_favorite_team" (
    "id" bigint generated by default as identity PRIMARY KEY,
    "user_id" BIGINT NOT NULL,
    "team_id" VARCHAR(64) NOT NULL,
    "display_order" INT DEFAULT 0,        -- 즐겨찾기 순서
    UNIQUE ("user_id", "team_id")          -- 중복 즐겨찾기 방지
);


CREATE TABLE IF NOT EXISTS "posts"
(
    "id"         bigint generated by default as identity primary key,
    "title"      varchar(255) not null,
    "content"    text         not null,
    "user_id"    bigint       not null,
    "created_dt" timestamp with time zone default now(),
    "updated_dt" timestamp with time zone default now(),
    "view_cnt"   bigint                   default 0,
    "like_cnt"   bigint                   default 0,
    "category"   varchar(255),
    "status"     varchar(100)
        constraint posts_status_check
            check ("status" IN ('PUBLIC', 'PRIVATE', 'DELETED'))
);

CREATE TABLE IF NOT EXISTS "files"
(
    "id"         bigint generated by default as identity primary key,
    "post_id"    bigint       not null,
    "file_name"  varchar(255) not null,
    "file_path"  varchar(255) not null,
    "created_dt" timestamp with time zone default now(),
    "updated_dt" timestamp with time zone default now(),
    "status"     varchar(100)
        constraint files_status_check
            check ("status" IN ('PUBLIC', 'PRIVATE', 'DELETED'))
);

CREATE TABLE IF NOT EXISTS "temp_table"
(
    "id"          bigint generated by default as identity primary key,
    "tamp_column" bigint not null,
    UNIQUE ("id", "tamp_column")
)



-- -- 사용자 테이블 (users)
-- CREATE TABLE users (
--    id BIGINT AUTO_INCREMENT PRIMARY KEY,
--    email VARCHAR(255) NOT NULL,
--    password VARCHAR(255),      -- 비밀번호 (소셜 로그인 사용자가 아닐 경우)
--    name VARCHAR(255),          -- 이름
--    profile_image_url TEXT,     -- 프로필 사진 URL (선택 사항)
--    created_dt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--    updated_dt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
-- );
--
-- -- 소셜 계정 테이블 (social_accounts)
-- CREATE TABLE social_accounts (
--  id BIGINT AUTO_INCREMENT PRIMARY KEY,
--  user_id BIGINT NOT NULL,                    -- users 테이블과의 관계
--  provider VARCHAR(50) NOT NULL,              -- 소셜 로그인 제공자 (Google, Facebook 등)
--  provider_user_id VARCHAR(255) NOT NULL,     -- 소셜 로그인 제공자의 고유 사용자 ID
--  access_token VARCHAR(255),                  -- 소셜 로그인 액세스 토큰 (필요시)
--  refresh_token VARCHAR(255),                 -- 소셜 로그인 리프레시 토큰 (필요시)
--  created_dt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
-- );
