-- create table "users" (
--      "id" bigint generated by default as identity,
--      "password" varchar(255),
--      "email" varchar(255),
--      "name" varchar(255),
--      "profile_image_url" varchar(255),
--      "created_dt" timestamp(6),
--      "updated_dt" timestamp(6),
--      primary key ("id")
-- );

INSERT INTO users (id, password, email, name) VALUES (1, 'password123', 'test@example.com', 'testuser');
INSERT INTO users (id, password, email, name) VALUES (2, 'password123', 'test2@example.com', 'testuser2');
