-- data.sql 보다 먼저 실행됨

CREATE TABLE IF NOT EXISTS "users" (
     "id" bigint generated by default as identity,
     "password" varchar(255),
     "email" varchar(255) unique,
     "name" varchar(255),
     "authority" varchar(255) default 'SCOPE_USER',
     "profile_image_url" varchar(255),
     "created_dt" timestamp(6),
     "updated_dt" timestamp(6),
     primary key ("id")
);

CREATE TABLE IF NOT EXISTS "leagues"
(
    id               BIGSERIAL PRIMARY KEY,
    league_id        VARCHAR(64)  NOT NULL UNIQUE,
    slug             VARCHAR(300) NOT NULL,
    name             VARCHAR(300) NOT NULL,
    region           VARCHAR(50),
    image            TEXT,
    priority         INT,
    display_position INT,
    display_status   VARCHAR(50),
    created_at       TIMESTAMP,
    updated_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "tournaments"
(
    id            BIGSERIAL PRIMARY KEY,
    tournament_id VARCHAR(64) NOT NULL UNIQUE,
    slug          VARCHAR(300),
    start_date    TIMESTAMP,
    end_date      TIMESTAMP,
    league_id     VARCHAR(64) NOT NULL
    -- 외래키 추가 가능: REFERENCES leagues(league_id)
);

CREATE TABLE IF NOT EXISTS "matches"
(
    id         BIGSERIAL PRIMARY KEY,
    match_id   VARCHAR(64) NOT NULL UNIQUE,
    league_id  VARCHAR(64) NOT NULL,
    tournament_id  VARCHAR(64),
    start_time TIMESTAMP,
    state      VARCHAR(50),
    block_name VARCHAR(100),
    game_count INT,
    strategy   VARCHAR(50)
    -- 외래키 추가 가능: REFERENCES leagues(league_id)
);

CREATE TABLE IF NOT EXISTS "match_teams"
(
    id        BIGSERIAL PRIMARY KEY,
    match_id  VARCHAR(64) NOT NULL,
    team_id   VARCHAR(64) NOT NULL,
    outcome    VARCHAR(20),
    game_wins INT
    -- 외래키 추가 가능: REFERENCES matches(match_id), teams(team_code)
);

CREATE TABLE IF NOT EXISTS "teams"
(
    id          BIGSERIAL PRIMARY KEY,
    team_id     VARCHAR(64) NOT NULL,
    slug        VARCHAR(150) NOT NULL,
    code        VARCHAR(64)  NOT NULL,
    name        VARCHAR(150) NOT NULL,
    image       TEXT         NOT NULL,
    league_id VARCHAR(64),
    unique (team_id)
);

alter table "teams"
    owner to jikim;


----------------------
CREATE TABLE IF NOT EXISTS "user_favorite_team" (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL,
    team_id VARCHAR(64) NOT NULL,
    display_order INT DEFAULT 0,        -- 즐겨찾기 순서
    UNIQUE (user_id, team_id)          -- 중복 즐겨찾기 방지
);

alter table "user_favorite_team"
    owner to jikim;


CREATE TABLE IF NOT EXISTS "posts"
(
    "id"         bigserial primary key,
    "title"      varchar(255) not null,
    "content"    text         not null,
    "user_id"    bigint       not null,
    "created_dt" timestamp with time zone default now(),
    "updated_dt" timestamp with time zone default now(),
    "view_cnt"   bigint                   default 0,
    "like_cnt"   bigint                   default 0,
    "category"   varchar(255),
    "status"     varchar(100)
        constraint posts_status_check
            check ((status)::text = ANY
                   ((ARRAY ['PUBLIC'::character varying, 'PRIVATE'::character varying, 'DELETED'::character varying])::text[]))
);

comment on table posts is '게시글';
comment on column posts.id is '게시글 고유 ID (자동 증가)';
comment on column posts.title is '게시글 제목 (최대 255자)';
comment on column posts.content is '게시글 내용 (길이 제한 없음)';
comment on column posts.user_id is '게시글 작성자 ID (users 테이블과 연관 가능)';
comment on column posts.created_dt is '게시글 작성 시간 (기본값: 현재 시간)';
comment on column posts.updated_dt is '게시글 수정 시간';
comment on column posts.view_cnt is '게시글 조회수';
comment on column posts.like_cnt is '게시글 좋아요 개수';
comment on column posts.category is '게시글 분류';
comment on column posts.status is '게시글 상태 (PUBLIC: 공개, PRIVATE: 비공개, DELETED: 삭제됨)';

alter table "posts"
    owner to jikim;

CREATE TABLE IF NOT EXISTS "files"
(
    "id"         bigserial primary key,
    "post_id"    bigint       not null,
    "file_name"  varchar(255) not null,
    "file_path"  varchar(255) not null,
    "created_dt" timestamp with time zone default now(),
    "updated_dt" timestamp with time zone default now(),
    "status"     varchar(100)
        constraint files_status_check
            check ((status)::text = ANY
                   ((ARRAY ['PUBLIC'::character varying, 'PRIVATE'::character varying, 'DELETED'::character varying])::text[]))
);

comment on table files is '첨부파일';
comment on column files.id is '파일ID';
comment on column files.post_id is '게시글ID';
comment on column files.file_name is '파일명';
comment on column files.file_path is '파일경로';
comment on column files.created_dt is '생성일';
comment on column files.updated_dt is '수정일';
comment on column files.status is '상태';

alter table files
    owner to jikim;

CREATE TABLE IF NOT EXISTS temp_table
(
    "id"          bigserial primary key,
    "tamp_column" bigint not null,
    UNIQUE ("id", "tamp_column")
)