-- data.sql 보다 먼저 실행됨

CREATE TABLE IF NOT EXISTS "users" (
     "id" bigint generated by default as identity,
     "password" varchar(255),
     "email" varchar(255) unique,
     "name" varchar(255),
     "authority" varchar(255) default 'SCOPE_USER',
     "profile_image_url" varchar(255),
     "password_version" integer default 1,
     "created_dt" timestamp(6),
     "updated_dt" timestamp(6),
     primary key ("id")
);

-- 마이그레이션: password_version 이전에 만들어진 기존 데이터베이스 보정.
-- 반드시 users 생성 이후에 둔다. 앞에 두면 빈 DB에서 "users 릴레이션 없음"으로
-- schema.sql 전체가 실패해 애플리케이션이 기동하지 못한다.
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS password_version integer DEFAULT 1;
UPDATE "users" SET password_version = 1 WHERE password_version IS NULL;

-- 마이그레이션: 권한 없이 가입된 계정 보정.
-- createUser가 authority를 채우지 않아 NULL로 저장됐고(컬럼 default는 JPA가 NULL을
-- 명시해 넣어 적용되지 않는다), 그 계정은 로그인 시 권한 파싱에서 막혀 401이 났다.
-- 가입은 성공했는데 로그인만 안 되는 상태라 사용자가 원인을 알 수 없다.
UPDATE "users" SET authority = 'SCOPE_USER' WHERE authority IS NULL OR btrim(authority) = '';

-- 리프레시 토큰. RefreshToken 엔티티가 user에 @OneToOne이라 user_id에 유니크가 걸린다.
-- 이 제약이 없으면 사용자당 토큰이 여러 개 쌓여 재로그인 시 조회가 어긋난다.
CREATE TABLE IF NOT EXISTS "refresh_tokens" (
     "id"          bigint generated by default as identity,
     "token"       varchar(255) not null,
     "user_id"     bigint,
     "expiry_date" timestamp(6) not null,
     "created_dt"  timestamp(6),
     primary key ("id"),
     constraint "uk_refresh_tokens_token" unique ("token"),
     constraint "uk_refresh_tokens_user_id" unique ("user_id"),
     constraint "fk_refresh_tokens_user" foreign key ("user_id") references "users" ("id")
);

comment on table "refresh_tokens" is '리프레시 토큰 (사용자당 1개)';

CREATE TABLE IF NOT EXISTS "leagues"
(
    id               BIGSERIAL PRIMARY KEY,
    league_id        VARCHAR(64)  NOT NULL UNIQUE,
    slug             VARCHAR(300) NOT NULL,
    name             VARCHAR(300) NOT NULL,
    region           VARCHAR(50),
    image            TEXT,
    priority         INT,
    display_position INT,
    display_status   VARCHAR(50),
    created_at       TIMESTAMP,
    updated_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "tournaments"
(
    id            BIGSERIAL PRIMARY KEY,
    tournament_id VARCHAR(64) NOT NULL UNIQUE,
    slug          VARCHAR(300),
    start_date    TIMESTAMP,
    end_date      TIMESTAMP,
    league_id     VARCHAR(64) NOT NULL
    -- 외래키 추가 가능: REFERENCES leagues(league_id)
);

CREATE TABLE IF NOT EXISTS "matches"
(
    id         BIGSERIAL PRIMARY KEY,
    match_id   VARCHAR(64) NOT NULL UNIQUE,
    league_id  VARCHAR(64) NOT NULL,
    tournament_id  VARCHAR(64),
    start_time TIMESTAMP,
    state      VARCHAR(50),
    block_name VARCHAR(100),
    game_count INT,
    strategy   VARCHAR(50),
    vod_url    TEXT
    -- 외래키 추가 가능: REFERENCES leagues(league_id)
);
-- 날짜 비교 조회 시 인덱스 범위 스캔 목적
-- 마이그레이션: 숨김 컬럼 도입 이전 데이터베이스 보정.
-- 반드시 matches 생성 이후에 둔다(빈 DB에서 릴레이션 없음으로 전체가 실패한다).
ALTER TABLE "matches" ADD COLUMN IF NOT EXISTS hidden_at TIMESTAMP;
ALTER TABLE "matches" ADD COLUMN IF NOT EXISTS hidden_reason VARCHAR(64);

-- 숨긴 경기는 목록 조회에서 빠지므로 부분 인덱스로 충분하다.
CREATE INDEX IF NOT EXISTS idx_matches_visible
    ON "matches" ("league_id", "start_time") WHERE hidden_at IS NULL;

DROP INDEX IF EXISTS idx_match_start_time;
CREATE INDEX idx_match_start_time ON "matches" ("start_time");


CREATE TABLE IF NOT EXISTS "match_teams"
(
    id        BIGSERIAL PRIMARY KEY,
    match_id  VARCHAR(64) NOT NULL,
    team_id   VARCHAR(64) NOT NULL,
    outcome    VARCHAR(20),
    game_wins INT
    -- 외래키 추가 가능: REFERENCES matches(match_id), teams(team_code)
);

-- 중복 데이터 정리 (고유 인덱스 생성 전)
DELETE FROM "match_teams"
WHERE id NOT IN (
    SELECT MIN(id)
    FROM "match_teams"
    GROUP BY match_id, team_id
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_match_teams_match_team
    ON "match_teams" (match_id, team_id);

CREATE TABLE IF NOT EXISTS "teams"
(
    id          BIGSERIAL PRIMARY KEY,
    team_id     VARCHAR(64) NOT NULL,
    slug        VARCHAR(150) NOT NULL,
    code        VARCHAR(64)  NOT NULL,
    name        VARCHAR(150) NOT NULL,
    image       TEXT         NOT NULL,
    league_id VARCHAR(64),
    unique (team_id)
);

alter table "teams"
    owner to jikim;


----------------------
CREATE TABLE IF NOT EXISTS "user_favorite_team" (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL,
    team_id VARCHAR(64) NOT NULL,
    display_order INT DEFAULT 0,        -- 즐겨찾기 순서
    UNIQUE (user_id, team_id)          -- 중복 즐겨찾기 방지
);

alter table "user_favorite_team"
    owner to jikim;


CREATE TABLE IF NOT EXISTS "user_league_orders"
(
    id            BIGSERIAL PRIMARY KEY,
    user_id       BIGINT      NOT NULL,
    league_id     VARCHAR(64) NOT NULL,
    display_order INT         NOT NULL,
    updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_id, league_id)
);

comment on table "user_league_orders" is '사용자별 리그 정렬 순서';
comment on column "user_league_orders".id is '고유 ID';
comment on column "user_league_orders".user_id is '사용자 ID (users 테이블 FK)';
comment on column "user_league_orders".league_id is '리그 ID (leagues 테이블 league_id)';
comment on column "user_league_orders".display_order is '정렬 순서 (0부터 시작)';
comment on column "user_league_orders".updated_at is '수정 일시';

-- owner_key: 알림 구독의 주체. 로그인 사용자는 'u:<userId>', 비로그인 기기는 'd:<deviceId>'.
-- 로그인 없이도 알림을 받을 수 있어야 해서 user_id 단일 키에서 이 형태로 일반화했다.
-- user_id는 기존 데이터 보존과 롤백을 위해 남겨두되 더 이상 조회 키로 쓰지 않는다.
CREATE TABLE IF NOT EXISTS "fcm_tokens"
(
    id          BIGSERIAL PRIMARY KEY,
    owner_key   VARCHAR(80)  NOT NULL,
    user_id     BIGINT,
    token       VARCHAR(512) NOT NULL,
    device_info TEXT,
    updated_at  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "match_alarms"
(
    id        BIGSERIAL PRIMARY KEY,
    owner_key VARCHAR(80) NOT NULL,
    user_id   BIGINT,
    match_id  VARCHAR(64) NOT NULL
);

-- 마이그레이션: refresh_tokens에 남은 옛 네이밍 잔재 컬럼 제거. (이슈 #34)
-- 반드시 위 CREATE TABLE 이후에 둔다.
--
-- 운영 refresh_tokens에는 예전 Hibernate 네이밍 전략이 만든 camelCase 컬럼이
-- 남아 있었다(expirydate = expiry_date, createddt = created_dt). 그중 expirydate가
-- NOT NULL이라, expiry_date에만 값을 넣는 지금의 INSERT가 전부 실패했다.
-- 그 결과 운영에서 아무도 로그인할 수 없었다.
--
-- 이 테이블은 CREATE TABLE IF NOT EXISTS라 정의를 고쳐도 기존 DB에는 반영되지
-- 않는다. 그래서 ALTER로 따로 보정한다.
--
-- 남기지 않고 지운다. 코드 어디에서도 참조하지 않는 고아 컬럼이고 값도 각각
-- expiry_date/created_dt와 중복이다. refresh token은 7일이면 만료되는 재발급
-- 가능한 데이터라, 최악의 경우라도 사용자가 다시 로그인하면 된다.
--
-- PL/pgSQL(DO 블록)로 일반화하지 말 것. spring.sql.init의 스크립트 분리기는
-- 달러 인용($$)을 몰라 내부 세미콜론에서 문장을 쪼개고,
-- continue-on-error가 꺼져 있어 그 순간 애플리케이션 기동이 통째로 실패한다.
ALTER TABLE "refresh_tokens" DROP COLUMN IF EXISTS "expirydate";
ALTER TABLE "refresh_tokens" DROP COLUMN IF EXISTS "createddt";

-- 마이그레이션: owner_key 도입 이전에 만들어진 데이터베이스 보정.
-- 반드시 위 CREATE TABLE 이후에 둔다(빈 DB에서 "릴레이션 없음"으로 전체가 실패한다).
ALTER TABLE "fcm_tokens"  ADD COLUMN IF NOT EXISTS owner_key VARCHAR(80);
ALTER TABLE "match_alarms" ADD COLUMN IF NOT EXISTS owner_key VARCHAR(80);

UPDATE "fcm_tokens"  SET owner_key = 'u:' || user_id WHERE owner_key IS NULL AND user_id IS NOT NULL;
UPDATE "match_alarms" SET owner_key = 'u:' || user_id WHERE owner_key IS NULL AND user_id IS NOT NULL;

-- 비로그인 구독은 user_id가 없다.
ALTER TABLE "fcm_tokens"  ALTER COLUMN user_id DROP NOT NULL;
ALTER TABLE "match_alarms" ALTER COLUMN user_id DROP NOT NULL;

-- 조회 키가 user_id에서 owner_key로 바뀌었으므로 유니크 제약도 옮긴다.
DROP INDEX IF EXISTS uq_fcm_tokens_user_token;
DROP INDEX IF EXISTS uq_match_alarms_user_match;

CREATE UNIQUE INDEX IF NOT EXISTS uq_fcm_tokens_owner_token
    ON "fcm_tokens" (owner_key, token);

CREATE UNIQUE INDEX IF NOT EXISTS uq_match_alarms_owner_match
    ON "match_alarms" (owner_key, match_id);

CREATE INDEX IF NOT EXISTS idx_match_alarms_match_id
    ON "match_alarms" (match_id);


CREATE TABLE IF NOT EXISTS "manual_match_overrides"
(
    id                  BIGSERIAL PRIMARY KEY,
    match_id            VARCHAR(64)  NOT NULL UNIQUE,
    override_start_time TIMESTAMP,
    override_block_name VARCHAR(100),
    lock_start_time     BOOLEAN      NOT NULL DEFAULT FALSE,
    lock_block_name     BOOLEAN      NOT NULL DEFAULT FALSE,
    updated_by          VARCHAR(100),
    updated_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "match_external_mapping"
(
    id                BIGSERIAL PRIMARY KEY,
    provider          VARCHAR(50)  NOT NULL,
    external_match_id VARCHAR(64)  NOT NULL,
    match_id          VARCHAR(64)  NOT NULL,
    updated_by        VARCHAR(100),
    updated_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_match_external_mapping_provider_external
    ON "match_external_mapping" (provider, external_match_id);

CREATE INDEX IF NOT EXISTS idx_match_external_mapping_match_id
    ON "match_external_mapping" (match_id);


CREATE TABLE IF NOT EXISTS "posts"
(
    "id"         bigserial primary key,
    "title"      varchar(255) not null,
    "content"    text         not null,
    "user_id"    bigint       not null,
    "created_dt" timestamp with time zone default now(),
    "updated_dt" timestamp with time zone default now(),
    "view_cnt"   bigint                   default 0,
    "like_cnt"   bigint                   default 0,
    "category"   varchar(255),
    "status"     varchar(100)
        constraint posts_status_check
            check ((status)::text = ANY
                   ((ARRAY ['PUBLIC'::character varying, 'PRIVATE'::character varying, 'DELETED'::character varying])::text[]))
);

comment on table posts is '게시글';
comment on column posts.id is '게시글 고유 ID (자동 증가)';
comment on column posts.title is '게시글 제목 (최대 255자)';
comment on column posts.content is '게시글 내용 (길이 제한 없음)';
comment on column posts.user_id is '게시글 작성자 ID (users 테이블과 연관 가능)';
comment on column posts.created_dt is '게시글 작성 시간 (기본값: 현재 시간)';
comment on column posts.updated_dt is '게시글 수정 시간';
comment on column posts.view_cnt is '게시글 조회수';
comment on column posts.like_cnt is '게시글 좋아요 개수';
comment on column posts.category is '게시글 분류';
comment on column posts.status is '게시글 상태 (PUBLIC: 공개, PRIVATE: 비공개, DELETED: 삭제됨)';

alter table "posts"
    owner to jikim;

CREATE SEQUENCE IF NOT EXISTS post_sequence
    START WITH 1
    INCREMENT BY 50;

CREATE TABLE IF NOT EXISTS "files"
(
    "id"         bigserial primary key,
    "post_id"    bigint       not null,
    "file_name"  varchar(255) not null,
    "file_path"  varchar(255) not null,
    "created_dt" timestamp with time zone default now(),
    "updated_dt" timestamp with time zone default now(),
    "status"     varchar(100)
        constraint files_status_check
            check ((status)::text = ANY
                   ((ARRAY ['PUBLIC'::character varying, 'PRIVATE'::character varying, 'DELETED'::character varying])::text[]))
);

comment on table files is '첨부파일';
comment on column files.id is '파일ID';
comment on column files.post_id is '게시글ID';
comment on column files.file_name is '파일명';
comment on column files.file_path is '파일경로';
comment on column files.created_dt is '생성일';
comment on column files.updated_dt is '수정일';
comment on column files.status is '상태';

alter table files
    owner to jikim;

CREATE TABLE IF NOT EXISTS temp_table
(
    "id"          bigserial primary key,
    "tamp_column" bigint not null,
    UNIQUE ("id", "tamp_column")
);
