name: "[CD] Deploy Basic BE SpringBoot TO AWS EC2"

on:
  push:
    branches:
      - main    # main 브랜치에 푸시될 때마다 실행됨

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      #uses: → 공식 액션(플러그인) 사용
      #run: → 직접 명령어 실행

      - name: "[1] SSH into server and deploy"
        uses: appleboy/ssh-action@v1.0.3  # SSH를 통해 서버에 배포
        with:
          host: ${{ secrets.SSH_HOST }}  # 서버 호스트
          username: ${{ secrets.SSH_USER }}  # 서버 사용자
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # 서버 SSH 키
          script: |
            # 서버 내에서 사용할 변수 설정
            REPO_URL="ghcr.io/${{ github.repository }}"
            CONTAINER_NAME="app_container"
            
            # GHCR 접근을 위한 로그인
            echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            
            # 최신 이미지 pull
            docker pull $REPO_URL:latest
            
            # 기존 컨테이너 종료 및 삭제
            docker stop $CONTAINER_NAME
            docker rm $CONTAINER_NAME
            
            # 최신 이미지로 컨테이너 실행
            docker run -d --name $CONTAINER_NAME -p 8080:8080 $REPO_URL:latest
            
            # 배포 후 컨테이너 동작 확인
            docker ps

