name: OIDC Test via SSM

on:
  pull_request:
    branches: [ main ] # 'main' 브랜치에 생긴 PR에 대해서 실행
    types:
      - opened  # PR이 처음 열릴 때만 실행

jobs:
  oidc-test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write     # OIDC 인증을 위한 필수
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-deploy-role
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy via SSM
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --instance-ids ${{ secrets.AWS_SSM_INSTANCE_ID }} \
            --parameters commands=["echo '배포 시작'"] \
            --region ${{ secrets.AWS_REGION }} 
