name: EC2 Connect Test with SSM

on:
  pull_request:
    branches:
      - main  # 'main' 브랜치에 생긴 PR에 대해서 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }} # 서울 리전

      - name: Run command via SSM
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --instance-ids ${{ secrets.AWS_SSM_INSTANCE_ID }} \
            --comment "Deploy app" \
            --parameters commands=["cd /home/ubuntu/app && git pull && ./deploy.sh"] \
            --region ap-northeast-2
